Repository AY2223S1-CS2113-W12-2/tp, pull requests merged in 2022-10, with the labels that each got.

#12 Add enum variables for Info and Error messages while refactoring UI output class
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/common/InfoMessages.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.Medium

#16 Inheritance on transaction
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Tasklist.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/data/transaction/Expense.java
  src/main/java/seedu/duke/data/transaction/Income.java
  src/main/java/seedu/duke/data/transaction/Transaction.java
Labels: type.Task, priority.High

#18 Add transaction to list
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/data/transaction/Expense.java
  src/main/java/seedu/duke/data/transaction/Income.java
  src/main/java/seedu/duke/data/transaction/Transaction.java
  src/main/java/seedu/duke/exception/AddTransactionMissingTagException.java
  src/main/java/seedu/duke/exception/AddTransactionUnknownTypeException.java
  src/main/java/seedu/duke/exception/MoolahException.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story

#46 Add ability to list all transactions
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/common/InfoMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/data/transaction/Transaction.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story

#50 Modified the TextUITest File.
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Story

#52 51 implement local date
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/common/DateFormats.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/data/transaction/Expense.java
  src/main/java/seedu/duke/data/transaction/Income.java
  src/main/java/seedu/duke/data/transaction/Transaction.java
  src/main/java/seedu/duke/exception/AddTransactionInvalidDateException.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Enhancement

#59 Organise and refractor source code for output-related functions
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ByeCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/PurgeCommand.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/common/InfoMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/data/transaction/Expense.java
  src/main/java/seedu/duke/data/transaction/Income.java
  src/main/java/seedu/duke/data/transaction/Transaction.java
  src/main/java/seedu/duke/exception/AddDeleteInvalidIndexException.java
  src/main/java/seedu/duke/exception/AddTransactionInvalidCategoryException.java
  src/main/java/seedu/duke/exception/AddTransactionInvalidDateException.java
  src/main/java/seedu/duke/exception/AddTransactionMissingTagException.java
  src/main/java/seedu/duke/exception/AddTransactionUnknownTypeException.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.High

#63 Add ability to find a specific transaction
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ByeCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/PurgeCommand.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/common/InfoMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/exception/FindTransactionMissingKeywordsException.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story

#64 Fix the exception handler for handling invalid or empty commands
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/exception/InvalidCommandException.java
  src/main/java/seedu/duke/exception/UnknownInputException.java
Labels: type.Bug, severity.Low

#66 Add ability to list savings for each category
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/command/GetCommand.java
  src/main/java/seedu/duke/common/InfoMessages.java
  src/main/java/seedu/duke/data/CategoryList.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/data/transaction/Category.java
  src/main/java/seedu/duke/data/transaction/Transaction.java
  src/test/java/seedu/duke/data/transaction/TransactionTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story

#67 Add tests for containNumeric() function
  src/main/java/seedu/duke/command/AddCommand.java
  src/test/java/seedu/duke/command/AddCommandTest.java
Labels: type.Task, severity.Low

#68 Add Junit Test for Purge and Resolving Conflicts
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/PurgeCommand.java
  src/main/java/seedu/duke/common/InfoMessages.java
  src/test/java/seedu/duke/DukeTest.java
  src/test/java/seedu/duke/command/PurgeCommandTest.java
  src/test/java/seedu/duke/data/transaction/TransactionTest.java
Labels: priority.High, type.Enhancement

#71 Refractor add command
  src/main/java/seedu/duke/command/AddCommand.java
Labels: type.Task, priority.Low

#72 30 help command
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ByeCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/GetCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/PurgeCommand.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story, priority.Medium

#75 Add handling of tags and parameters with exceptions
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/exception/AddTransactionExtraTagException.java
  src/main/java/seedu/duke/exception/AddTransactionMissingParameterException.java
  src/test/java/seedu/duke/command/AddCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Enhancement

#79 Add assertions for Find and Stats command classes, and remove some redundant lines
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/StatsCommand.java
Labels: type.Task, priority.Low

#81 78 Separation of Concern for command and parser
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/CommandTag.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/common/Utilities.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/data/transaction/Expense.java
  src/main/java/seedu/duke/data/transaction/Income.java
  src/main/java/seedu/duke/exception/EmptyParameterException.java
  src/main/java/seedu/duke/exception/EntryNumberNotNumericException.java
  src/main/java/seedu/duke/exception/InputDuplicateTagException.java
  src/main/java/seedu/duke/exception/InputMissingTagException.java
  src/main/java/seedu/duke/exception/InputUnsupportedTagException.java
  src/main/java/seedu/duke/exception/InvalidIndexException.java
  src/main/java/seedu/duke/exception/UnknownHelpOptionException.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/parser/ParameterParser.java
  src/test/java/seedu/duke/command/AddCommandTest.java
  src/test/java/seedu/duke/common/UtilitiesTest.java
  src/test/java/seedu/duke/parser/ParameterParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.High

#82 Fix the severe bug of "stats/s categories" command and prepare other parts of the program for release
  docs/AboutUs.md
  docs/team/chiathinhong.png
  docs/team/chuahanyongdarren.png
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ByeCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/PurgeCommand.java
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/common/InfoMessages.java
  src/main/java/seedu/duke/data/CategoryList.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/parser/ParameterParser.java
Labels: type.Bug, type.Task, priority.High, severity.High

#85 Add log messages for parameter parser
  build.gradle
  src/main/java/seedu/duke/parser/ParameterParser.java
Labels: type.Task, priority.Low

#88 Add Assertions and Loggings
  docs/AboutUs.md
  docs/team/brianwongyunlong.png
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/PurgeCommand.java
Labels: priority.High, type.Enhancement

#89 Reclaim code for team members to ensure RepoSense compatibility
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ByeCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/CommandTag.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/PurgeCommand.java
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/common/DateFormats.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/common/InfoMessages.java
  src/main/java/seedu/duke/data/CategoryList.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/data/transaction/Category.java
  src/main/java/seedu/duke/data/transaction/Expense.java
  src/main/java/seedu/duke/data/transaction/Income.java
  src/main/java/seedu/duke/data/transaction/Transaction.java
  src/main/java/seedu/duke/exception/AddTransactionInvalidAmountException.java
  src/main/java/seedu/duke/exception/EmptyParameterException.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/parser/ParameterParser.java
  src/test/java/seedu/duke/command/AddCommandTest.java
  src/test/java/seedu/duke/command/PurgeCommandTest.java
  src/test/java/seedu/duke/common/UtilitiesTest.java
  src/test/java/seedu/duke/data/transaction/TransactionTest.java
  src/test/java/seedu/duke/parser/ParameterParserTest.java
Labels: type.Task, priority.High

#95 Add storage feature
  .gitignore
  META-INF/MANIFEST.MF
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/PurgeCommand.java
  src/main/java/seedu/duke/common/DateFormats.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/data/transaction/Expense.java
  src/main/java/seedu/duke/data/transaction/Income.java
  src/main/java/seedu/duke/data/transaction/Transaction.java
  src/main/java/seedu/duke/exception/StorageInputCorruptedException.java
  src/main/java/seedu/duke/exception/StorageWriteErrorException.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/parser/ParameterParser.java
  text-ui-test/EXPECTED.TXT
Labels: type.Story, priority.Medium

#96 Change incorrect comments and add constants
  src/main/java/seedu/duke/Storage.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.Low

#97 Add heading structure for Developer Guide
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Documentation

#100 DG: Add implementation for Transaction object
  docs/DeveloperGuide.md
  docs/diagram/Transaction.puml
  docs/images/TransactionClassDiagram.png
Labels: priority.Medium, type.Documentation

#102 Developer guide write up for data component and help command
  docs/DeveloperGuide.md
  docs/diagram/DataComponentClassDiagram.puml
  docs/diagram/HelpClassDiagram.puml
  docs/diagram/Style.puml
  docs/diagram/Transaction.puml
  docs/diagram/TransactionListSequenceDiagram.puml
  docs/images/DataComponentClassDiagram.png
  docs/images/HelpClassDiagram.png
  docs/images/TransactionListSequenceDiagram.png
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/PurgeCommand.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/data/transaction/Transaction.java
Labels: type.Documentation

#101 Add AddCommand description to Developer Guide
  docs/DeveloperGuide.md
  docs/diagram/AddCommand.puml
  docs/diagram/AddCommandExternalClasses.puml
  docs/images/AddCommandClassDiagram.png
  docs/images/AddCommandDetailedClassDiagram.png
Labels: priority.Medium, type.Documentation

#105 DG: Add implementation (draft) for Find Command and UI Component, and fix issues with line breaks
  docs/DeveloperGuide.md
  docs/diagram/FindCommandSequenceDiagram.puml
  docs/diagram/Transaction.puml
  docs/diagram/UiComponentClassDiagram.puml
  docs/images/FindCommandSequenceDiagram.png
  docs/images/TransactionClassDiagram.png
  docs/images/UiComponentClassDiagram.png
Labels: priority.Medium, type.Documentation

#108 Add javadocs in help command and parameter parser classes
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/PurgeCommand.java
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/parser/ParameterParser.java
Labels: type.Documentation

#114 111 budget implementation
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/common/Constants.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/common/InfoMessages.java
  src/main/java/seedu/duke/data/Budget.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/data/transaction/Transaction.java
  src/main/java/seedu/duke/exception/InputTransactionInvalidAmountException.java
  src/main/java/seedu/duke/exception/MaximumTransactionCountException.java
  src/main/java/seedu/duke/parser/ParameterParser.java
  src/test/java/seedu/duke/parser/ParameterParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Story, priority.Medium

#115 Add Stats Insights, and lastNPeriod
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/CommandTag.java
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/common/InfoMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/exception/StatsInvalidNumberException.java
  src/main/java/seedu/duke/exception/StatsInvalidPeriodException.java
  src/main/java/seedu/duke/parser/ParameterParser.java
Labels: priority.High, type.Story

#116 Improve date helper functions and edit some tags and exceptions for universal usage
  src/main/java/seedu/duke/command/CommandTag.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/common/Constants.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/data/Budget.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/exception/InputMissingTagException.java
  src/main/java/seedu/duke/exception/InvalidIndexException.java
  src/main/java/seedu/duke/exception/ListStatsMissingTagException.java
  src/main/java/seedu/duke/exception/StatsInvalidMonthException.java
  src/main/java/seedu/duke/exception/StatsInvalidYearException.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/parser/ParameterParser.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Medium

#119 Organize authorship comments for UI class
  src/main/java/seedu/duke/Ui.java
Labels: type.Task, priority.Low

#120 Update Aboutus
  docs/AboutUs.md
  docs/team/paulsolomonlowsien.png
Labels: priority.Low, type.Documentation

#124 Added functionalities of Edit Command
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/common/InfoMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/data/transaction/Transaction.java
Labels: priority.High, type.Story, type.Enhancement

#123 Add storage support for BudgetCommand
  data/duke.txt
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/command/BudgetCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/exception/StorageFileCorruptedBudgetException.java
  src/main/java/seedu/duke/exception/StorageFileCorruptedTransactionException.java
  src/test/java/seedu/duke/command/BudgetCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Story, priority.Medium

#122 Add ability to list transactions by defined period
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/ListAndStatsCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/exception/FindTransactionMissingKeywordsException.java
  src/main/java/seedu/duke/exception/GlobalInvalidMonthException.java
  src/main/java/seedu/duke/exception/GlobalMissingPeriodNumberTagException.java
  src/main/java/seedu/duke/exception/GlobalMissingYearTagException.java
  src/main/java/seedu/duke/exception/InputTransactionInvalidTypeException.java
  src/main/java/seedu/duke/exception/StatsInvalidTypeException.java
  src/main/java/seedu/duke/parser/ParameterParser.java
Labels: type.Story, priority.Medium

#126 Add ability to view the monthly expenditure and spending habits comments in expenditure summary
  data/duke.txt
  docs/diagram/FindCommandClassDiagram.puml
  src/main/java/seedu/duke/command/ListAndStatsCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/common/DateFormats.java
  src/main/java/seedu/duke/common/InfoMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/exception/GlobalMissingPeriodNumberTagException.java
  src/main/java/seedu/duke/exception/GlobalMissingYearTagException.java
  src/main/java/seedu/duke/parser/ParameterParser.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#127 Add Storage Description
  docs/DeveloperGuide.md
  docs/diagram/StorageComponent.puml
  docs/images/StorageComponentClassDiagram.png
Labels: priority.Medium, type.Documentation

#129 34 money managing tips
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/BudgetCommand.java
  src/main/java/seedu/duke/command/ByeCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/PurgeCommand.java
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/common/DateFormats.java
  src/main/java/seedu/duke/common/InfoMessages.java
  src/main/java/seedu/duke/data/Budget.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/data/transaction/Category.java
  src/main/java/seedu/duke/data/transaction/Transaction.java
  src/test/java/seedu/duke/data/BudgetTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, type.Story, type.Enhancement, priority.Medium, severity.Medium

#134 Improve feature-packed Stats command and fix related bugs
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/BudgetCommand.java
  src/main/java/seedu/duke/command/ByeCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/ListAndStatsCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/common/Constants.java
  src/main/java/seedu/duke/common/DateFormats.java
  src/main/java/seedu/duke/common/InfoMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/data/transaction/Category.java
  src/main/java/seedu/duke/parser/ParameterParser.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Bug, type.Enhancement, priority.Medium, severity.Medium

#135 Add Stats fix
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/data/TransactionList.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Bug, type.Enhancement, priority.Medium, severity.Medium

#136 Add JUnit Tests for V2.0 I
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/ListAndStatsCommand.java
  src/main/java/seedu/duke/command/StatsCommand.java
  src/test/java/seedu/duke/command/FindCommandTest.java
  src/test/java/seedu/duke/command/ListCommandTest.java
  src/test/java/seedu/duke/command/StatsCommandTest.java
  src/test/java/seedu/duke/parser/CommandParserTest.java
  src/test/java/seedu/duke/parser/ParameterParserTest.java
Labels: type.Task, priority.Medium

#137 Reclaim authorship for Brian in EditCommand class
  src/main/java/seedu/duke/command/EditCommand.java
Labels: type.Task, priority.Low

#138 Describe program architecture in developer guide
  docs/DeveloperGuide.md
  docs/diagram/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
Labels: type.Documentation

#139 Update data component in developer guide for budget class
  docs/DeveloperGuide.md
  docs/diagram/DataComponentClassDiagram.puml
  docs/diagram/TransactionListSequenceDiagram.puml
  docs/images/DataComponentClassDiagram.png
  docs/images/TransactionListSequenceDiagram.png
  src/main/java/seedu/duke/data/transaction/Transaction.java
Labels: type.Documentation

#141 DG Additions
  docs/DeveloperGuide.md
  docs/diagram/CommandComponentClassDiagram.puml
  docs/images/CommandComponentClassDiagram.png
Labels: type.Documentation

#142 UG: Add heading structure for User Guide
  docs/README.md
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#144 DG: Update the developer guide's appendices based on previous team meeting notes
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Documentation

#148 Fixed Param Errors
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/exception/StatsInvalidNumberException.java
  src/main/java/seedu/duke/parser/ParameterParser.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, priority.High

#149 UG command format help budget
  docs/UserGuide.md
  src/main/java/seedu/duke/common/Constants.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/parser/ParameterParser.java
  text-ui-test/EXPECTED.TXT
Labels: type.Documentation

#150 UG: Add content for Introduction, Setting Up, List and Find Commands
  docs/UserGuide.md
  docs/images/MoolahManagerDownload.png
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/data/transaction/Transaction.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Documentation

#151 Add details for the User Guide
  docs/UserGuide.md
Labels: type.Documentation

#152 Move help information to Help Messages Enum class and sync descriptions to be in-line with UG
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/BudgetCommand.java
  src/main/java/seedu/duke/command/ByeCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/PurgeCommand.java
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/common/HelpMessages.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task, priority.Low

#153 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#155 Update user guide as recommended by @chydarren and modify help message
  docs/UserGuide.md
  src/main/java/seedu/duke/common/HelpMessages.java
  text-ui-test/EXPECTED.TXT
Labels: type.Documentation

#156 Add user guide description
  data/duke.txt
  docs/UserGuide.md
Labels: type.Documentation

#202 Ped fix
  data/duke.txt
  docs/UserGuide.md
  src/main/java/seedu/duke/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: severity.VeryLow, type.Suggestion, type.DocumentationBug

#203 Add more follow up edits to DG based on comments
  docs/DeveloperGuide.md
  docs/diagram/DeleteCommandSequenceDiagram.puml
  docs/images/DeleteCommandSequenceDiagram.png
Labels: type.Documentation, type.DocumentationBug

#204 Modify Find function to ignore case-sensitivity and compare only descriptions
  src/main/java/seedu/duke/data/TransactionList.java
Labels: type.Enhancement, priority.Medium, type.Suggestion

#207 Update ParameterParser.java
  src/main/java/seedu/duke/parser/ParameterParser.java
Labels: type.Bug, severity.Low

#206 Add Constants to replace magic values
  data/duke.txt
  src/main/java/seedu/duke/common/Constants.java
  src/main/java/seedu/duke/parser/ParameterParser.java
Labels: type.Task

#208 Add stats fix
  data/duke.txt
  docs/UserGuide.md
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/common/InfoMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, priority.High, severity.High

#209 Fix error messages to redirect users to the help command
  .gitignore
  src/main/java/seedu/duke/common/ErrorMessages.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Suggestion

#218 Budget improvement
  .gitignore
  data/duke.txt
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/ListAndStatsCommand.java
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/common/InfoMessages.java
  src/main/java/seedu/duke/data/Budget.java
  src/main/java/seedu/duke/data/TransactionList.java
  text-ui-test/EXPECTED.TXT
Labels: type.Story, type.Enhancement, priority.Medium, severity.VeryLow

#224 Fix Sequence Diagram
  docs/DeveloperGuide.md
  docs/diagram/ListCommandSequenceDiagram.puml
  docs/images/ListCommandSequenceDiagram.png
  text-ui-test/EXPECTED.TXT
Labels: type.Documentation

#225 Add improvements for List and Find Commands
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/ListAndStatsCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/common/Constants.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/common/InfoMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/data/transaction/Transaction.java
  src/main/java/seedu/duke/exception/GlobalIndexNotNumericException.java
  src/main/java/seedu/duke/exception/GlobalUnsupportedTagCombinationException.java
  src/main/java/seedu/duke/parser/ParameterParser.java
  src/test/java/seedu/duke/command/ListCommandTest.java
  src/test/java/seedu/duke/command/StatsCommandTest.java
  src/test/java/seedu/duke/data/TransactionListTest.java
  src/test/java/seedu/duke/data/transaction/TransactionTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Bug, type.Story, type.Enhancement, priority.Medium, severity.VeryLow

#226 Add Project Portfolio Page (PPP) file
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/chiathinhong.md
  docs/team/wcwy.md
Labels: type.Documentation
