Repository AY2223S1-CS2113-W12-2/tp, pull requests merged in 2022-11, with the labels that each got.

#227 Add Project Portfolio Page (PPP) file
  docs/AboutUs.md
  docs/team/chuahanyongdarren.md
  docs/team/chydarren.md
  docs/team/wcwy.md
  text-ui-test/EXPECTED.TXT
Labels: type.Documentation

#228 Add personal PPP
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/chinhan99.md
  docs/team/yongchinhan.md
Labels: type.Documentation

#229 Added PPP
  docs/AboutUs.md
  docs/team/paullow.md
  docs/team/paullowse.md
Labels: priority.Medium, type.Documentation

#232 Adding more DG for Various Commands
  docs/DeveloperGuide.md
  docs/diagram/ByeCommand.puml
  docs/diagram/ByeCommandSequenceDiagram.puml
  docs/diagram/DeleteCommandSequenceDiagram.puml
  docs/diagram/EditCommand.puml
  docs/diagram/EditCommandSequenceDiagram.puml
  docs/diagram/PurgeCommandSequenceDiagram.puml
  docs/images/ByeCommandClassDiagram.png
  docs/images/ByeCommandSequenceDiagram.png
  docs/images/EditCommand.png
  docs/images/EditCommandSequenceDiagram.png
  docs/images/PurgeCommandSequenceDiagram.png
  src/main/java/seedu/duke/command/EditCommand.java
Labels: type.Documentation

#233 Add sequence diagram for Add command
  docs/DeveloperGuide.md
  docs/diagram/AddCommandSequenceDiagram.puml
  docs/images/AddCommandSequenceDiagram.png
Labels: type.Documentation

#234 199 help command enhancement
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/BudgetCommand.java
  src/main/java/seedu/duke/command/ByeCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/CommandTag.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/PurgeCommand.java
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/common/HelpMessages.java
  src/main/java/seedu/duke/exception/HelpUnknownCommandWordException.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/parser/ParameterParser.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story, type.Enhancement, priority.Medium, type.Suggestion

#236 Fix constants as per @dranov's comments
  src/main/java/seedu/duke/Storage.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/data/TransactionList.java
Labels: severity.Medium

#238 Improve Find Command and Finalize the User Guide
  docs/UserGuide.md
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/CommandTag.java
  src/main/java/seedu/duke/command/FindCommand.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/common/HelpMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/exception/FindTransactionMissingKeywordsException.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/parser/ParameterParser.java
  src/test/java/seedu/duke/command/FindCommandTest.java
  src/test/java/seedu/duke/common/UtilitiesTest.java
  src/test/java/seedu/duke/parser/ParameterParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement, priority.Medium, type.Documentation

#240 Update DG Diagrams and formatting structure
  docs/DeveloperGuide.md
  docs/diagram/AddCommandClassDiagram.puml
  docs/diagram/AddCommandExternalClasses.puml
  docs/diagram/AddCommandSequenceDiagram.puml
  docs/diagram/ByeCommandClassDiagram.puml
  docs/diagram/ByeCommandSequenceDiagram.puml
  docs/diagram/CommonComponentClassDiagram.puml
  docs/diagram/DeleteCommandClassDiagram.puml
  docs/diagram/DeleteCommandSequenceDiagram.puml
  docs/diagram/EditCommandClassDiagram.puml
  docs/diagram/EditCommandSequenceDiagram.puml
  docs/diagram/FindCommandClassDiagram.puml
  docs/diagram/FindCommandSequenceDiagram.puml
  docs/diagram/ListCommandSequenceDiagram.puml
  docs/diagram/ParserClassDiagram.puml
  docs/diagram/PurgeCommandClassDiagram.puml
  docs/diagram/PurgeCommandSequenceDiagram.puml
  docs/diagram/StorageComponentClassDiagram.puml
  docs/diagram/Style.puml
  docs/diagram/Transaction.puml
  docs/diagram/TransactionClassDiagram.puml
  docs/diagram/TransactionListSequenceDiagram.puml
  docs/diagram/UiComponentClassDiagram.puml
  docs/images/AddCommandClassDiagram.png
  docs/images/AddCommandDetailedClassDiagram.png
  docs/images/AddCommandSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/ByeCommandClassDiagram.png
  docs/images/ByeCommandSequenceDiagram.png
  docs/images/CommandComponentClassDiagram.png
  docs/images/CommonComponentClassDiagram.png
  docs/images/DataComponentClassDiagram.png
  docs/images/DeleteCommandClassDiagram.png
  docs/images/DeleteCommandSequenceDiagram.png
  docs/images/EditCommand.png
  docs/images/EditCommandClassDiagram.png
  docs/images/EditCommandSequenceDiagram.png
  docs/images/FindCommandSequenceDiagram.png
  docs/images/HelpClassDiagram.png
  docs/images/HelpCommandClassDiagram.png
  docs/images/HelpCommandSequenceDiagram.png
  docs/images/HelpSequenceDiagram.png
  docs/images/ListCommandSequenceDiagram.png
  docs/images/ParsersClassDiagram.png
  docs/images/PurgeCommandClassDiagram.png
  docs/images/PurgeCommandSequenceDiagram.png
  docs/images/StorageComponentClassDiagram.png
  docs/images/TransactionClassDiagram.png
  docs/images/TransactionListSequenceDiagram.png
  docs/images/UiComponentClassDiagram.png
Labels: priority.Medium, type.Documentation

#241 Changes made to Edit Command
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/exception/EditCommandEmptyTagsException.java
  src/main/java/seedu/duke/exception/EditCommandUnchangedException.java
Labels: priority.High, type.Enhancement, severity.High

#242 239 bug fix list sorting
  docs/UserGuide.md
  src/main/java/seedu/duke/command/ListAndStatsCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/common/HelpMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/test/java/seedu/duke/data/TransactionListTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, type.Task, severity.Medium

#243 Documentation enhancement
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagram/ArchitectureSequenceDiagram.puml
  docs/diagram/DataComponentClassDiagram.puml
  docs/diagram/HelpClassDiagram.puml
  docs/diagram/HelpSequenceDiagram.puml
  docs/diagram/TransactionListSequenceDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DataComponentClassDiagram.png
  docs/images/EditCommandClassDiagram.png
  docs/images/HelpCommandClassDiagram.png
  docs/images/HelpCommandSequenceDiagram.png
  docs/images/TransactionListSequenceDiagram.png
  docs/team/brian-vb.md
  docs/team/chinhan99.md
  docs/team/chydarren.md
  docs/team/paullowse.md
  docs/team/wcwy.md
Labels: type.Documentation

#245 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.Low, type.Documentation

#246 Update UG and DG for Find and List, Fix Bugs for Transactions with Indexes and Amount Values
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagram/FindCommandSequenceDiagram.puml
  docs/diagram/Style.puml
  docs/images/FindCommandSequenceDiagram.png
  src/main/java/seedu/duke/command/ListAndStatsCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/StatsCommand.java
  src/main/java/seedu/duke/common/Constants.java
  src/main/java/seedu/duke/common/InfoMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/test/java/seedu/duke/command/ListCommandTest.java
  src/test/java/seedu/duke/data/TransactionListTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Medium, severity.Medium, type.Documentation

#247 Final Changes to Edit Command and others
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/PurgeCommand.java
  src/main/java/seedu/duke/common/ErrorMessages.java
  src/main/java/seedu/duke/data/TransactionList.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, priority.High, severity.High

#248 Add improvements to DG Find and Stats command sections
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/diagram/FindCommandClassDiagram.puml
  docs/diagram/FindCommandSequenceDiagram.puml
  docs/diagram/StatsCommandClassDiagram.puml
  docs/diagram/StatsCommandMonthlyExpenditureSequenceDiagram.puml
  docs/diagram/StatsCommandSequenceDiagram.puml
  docs/diagram/StatsCommandTimeInsightsSequenceDiagram.puml
  docs/images/FindCommandClassDiagram.png
  docs/images/FindCommandSequenceDiagram.png
  docs/images/StatsCommandClassDiagram.png
  docs/images/StatsCommandMonthlyExpenditureSequenceDiagram.png
  docs/images/StatsCommandSequenceDiagram.png
  docs/images/StatsCommandTimeInsightsSequenceDiagram.png
  docs/images/logo.png
  docs/team/chydarren.md
Labels: priority.Medium, type.Documentation

#249 Fix minor bug in spending habit comment
  src/main/java/seedu/duke/data/TransactionList.java
Labels: type.Bug, severity.Low

#250 Thin Hong's final update
  docs/DeveloperGuide.md
  docs/images/HelpCommandClassDiagram.png
  src/main/java/seedu/duke/command/BudgetCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/common/HelpMessages.java
  src/main/java/seedu/duke/common/InfoMessages.java
  src/main/java/seedu/duke/data/Budget.java
  src/main/java/seedu/duke/data/TransactionList.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/parser/ParameterParser.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/data/BudgetTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Medium, type.Documentation, type.Suggestion

#251 Fix DG figure issues
  docs/DeveloperGuide.md
  docs/images/DataComponentClassDiagram.png
  docs/images/DeleteCommandSequenceDiagram.png
  docs/images/EditCommandSequenceDiagram.png
  docs/images/ListCommandSequenceDiagram.png
Labels: severity.VeryLow, type.DocumentationBug

#253 Darren's Final Update to Moolah Manager Application
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagram/FindCommandClassDiagram.puml
  docs/diagram/StatsCommandSequenceDiagram.puml
  docs/diagram/Style.puml
  docs/images/AddCommandExternalClasses.png
  docs/images/FindCommandClassDiagram.png
  docs/images/StatsCommandClassDiagram.png
  docs/images/StatsCommandMonthlyExpenditureSequenceDiagram.png
  docs/images/StatsCommandSequenceDiagram.png
  docs/images/StatsCommandTimeInsightsSequenceDiagram.png
  docs/images/StorageComponentClassDiagram.png
  docs/images/TransactionClassDiagram.png
  docs/images/UiComponentClassDiagram.png
  src/main/java/seedu/duke/data/TransactionList.java
Labels: priority.Medium, type.Documentation

#254 Update PPP formatting
  docs/team/chinhan99.md
Labels: type.Documentation

#256 Updated PPP and UG.
  docs/UserGuide.md
  docs/team/chinhan99.md
  src/main/java/seedu/duke/parser/ParameterParser.java
Labels: type.Documentation

#257 Class Diagrams Revamp
  docs/DeveloperGuide.md
  docs/diagram/ByeCommandClassDiagram.puml
  docs/diagram/CommandComponentClassDiagram.puml
  docs/diagram/DeleteCommandClassDiagram.puml
  docs/diagram/EditCommandClassDiagram.puml
  docs/diagram/PurgeCommandClassDiagram.puml
  docs/images/ByeCommandClassDiagram.png
  docs/images/CommandComponentClassDiagram.png
  docs/images/DeleteCommandClassDiagram.png
  docs/images/EditCommandClassDiagram.png
  docs/images/PurgeCommandClassDiagram.png
Labels: type.Documentation

#258 Update size of my diagrams
  docs/DeveloperGuide.md
  docs/images/MoolahManagerDownload.png
Labels: priority.Medium, type.Documentation

#259 Fix storage date parse bug
  src/main/java/seedu/duke/Storage.java
Labels: type.Bug, severity.Medium

#260 Add missing tag for help message and rephrase unclear words used
  docs/UserGuide.md
  src/main/java/seedu/duke/common/HelpMessages.java
  text-ui-test/EXPECTED.TXT
Labels: severity.VeryLow, type.Flaw

#261 DG changes for Edit and Delete
  docs/DeveloperGuide.md
  docs/diagram/DeleteCommandSequenceDiagram.puml
  docs/diagram/EditCommandSequenceDiagram.puml
  docs/images/DeleteCommandSequenceDiagram.png
  docs/images/EditCommandSequenceDiagram.png
Labels: type.Documentation

#262 Implement sorted monthly expenditure using a sorted treemap
  docs/diagram/StatsCommandMonthlyExpenditureSequenceDiagram.puml
  docs/images/StatsCommandMonthlyExpenditureSequenceDiagram.png
  src/main/java/seedu/duke/data/TransactionList.java
Labels: type.Enhancement, priority.Medium

#263 Final PPP Push
  docs/team/brian-vb.md
Labels: type.Documentation

#264 Fix minor sequence diagram issue pre-release
  docs/diagram/StatsCommandMonthlyExpenditureSequenceDiagram.puml
  docs/images/StatsCommandMonthlyExpenditureSequenceDiagram.png
Labels: severity.VeryLow

#265 Fix DG outdated value
  docs/DeveloperGuide.md
  docs/diagram/FindCommandClassDiagram.puml
  docs/diagram/Style.puml
  docs/images/FindCommandClassDiagram.png
Labels: severity.VeryLow
